In [38]:
import pandas as pd

In [28]:
#Reading datasets
customers_df = pd.read_csv('olist_customers_dataset.csv')
order_items_df = pd.read_csv('olist_order_items_dataset.csv')
geolocation_df = pd.read_csv('olist_geolocation_dataset.csv')
order_payments_df = pd.read_csv('olist_order_payments_dataset.csv')
order_reviews_df = pd.read_csv('olist_order_reviews_dataset.csv')
orders_df = pd.read_csv('olist_orders_dataset.csv')
products_df = pd.read_csv('olist_products_dataset.csv')
sellers_df = pd.read_csv('olist_sellers_dataset.csv')

df_list = [customers_df, order_items_df, geolocation_df, order_payments_df,
           order_reviews_df, orders_df, products_df, sellers_df]

In [21]:
#Checking for missing values
for df in df_list:
    missing_values = df.isnull().sum()
    print(missing_values[missing_values>0])

Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
Series([], dtype: int64)
review_comment_title      87656
review_comment_message    58247
dtype: int64
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
Series([], dtype: int64)

In [31]:
#Handling missing values in 'order_reviews_df'
order_reviews_df['review_comment_title'] = order_reviews_df['review_comment_title'].fillna('Sem titulo')
order_reviews_df['review_comment_message'] = order_reviews_df['review_comment_message'].fillna('Sem mensagem')
order_reviews_df.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,Sem titulo,Sem mensagem,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,Sem titulo,Sem mensagem,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,Sem titulo,Sem mensagem,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,Sem titulo,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,Sem titulo,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [76]:
#Handling missing values in 'orders_df'
missing_values = orders_df.isnull().sum()
missing_values = missing_values[missing_values>0]
mv_cols = missing_values.index
#orders_df[mv_cols].isnull().any()
for col in mv_cols:
    print(f"Linhas com valores faltantes na coluna '{col}':")
    missing_rows = orders_df[orders_df[col].isnull()]
    print(missing_rows)
    print("\n")
#missing_values = orders[orders.isna().any(axis=1)]

Linhas com valores faltantes na coluna 'order_approved_at':
                               order_id                       customer_id  \
1130   00b1cb0320190ca0daa2c88b35206009  3532ba38a3fd242259a514ac2b6ae6b6
1801   ed3efbd3a87bea76c2812c66a0b32219  191984a8ba4cbb2145acb4fe35b69664
1868   df8282afe61008dc26c6c31011474d02  aa797b187b5466bc6925aaaa4bb3bed1
2029   8d4c637f1accf7a88a4555f02741e606  b1dd715db389a2077f43174e7a675d07
2161   7a9d4c7f9b068337875b95465330f2fc  7f71ae48074c0cfec9195f88fcbfac55
...                                 ...                               ...
97696  5a00b4d35edffc56b825c3646a99ba9d  6a3bdf004ca96338fb5fad1b8d93c2e6
98415  227c804e2a44760671a6a5697ea549e4  62e7477e75e542243ee62a0ba73f410f
98909  e49e7ce1471b4693482d40c2bd3ad196  e4e7ab3f449aeb401f0216f86c2104db
99283  3a3cddda5a7c27851bd96c3313412840  0b0d6095c5555fe083844281f6b093bb
99347  a89abace0dcc01eeb267a9660b5ac126  2f0524a7b1b3845a1a57fcf3910c4333

      order_status order_purchase_timestamp order_approved_at  \
1130      canceled      2018-08-28 15:26:39               NaN
1801      canceled      2018-09-20 13:54:16               NaN
1868      canceled      2017-03-04 12:14:30               NaN
2029      canceled      2018-08-29 16:27:49               NaN
2161      canceled      2017-05-01 16:12:39               NaN
...            ...                      ...               ...
97696     canceled      2017-07-02 15:38:46               NaN
98415     canceled      2017-09-28 15:02:56               NaN
98909     canceled      2018-08-07 11:16:28               NaN
99283     canceled      2018-08-31 16:13:44               NaN
99347     canceled      2018-09-06 18:45:47               NaN

      order_delivered_carrier_date order_delivered_customer_date  \
1130                           NaN                           NaN
1801                           NaN                           NaN
1868                           NaN                           NaN
2029                           NaN                           NaN
2161                           NaN                           NaN
...                            ...                           ...
97696                          NaN                           NaN
98415                          NaN                           NaN
98909                          NaN                           NaN
99283                          NaN                           NaN
99347                          NaN                           NaN

      order_estimated_delivery_date
1130            2018-09-12 00:00:00
1801            2018-10-17 00:00:00
1868            2017-04-10 00:00:00
2029            2018-09-13 00:00:00
2161            2017-05-30 00:00:00
...                             ...
97696           2017-07-25 00:00:00
98415           2017-10-16 00:00:00
98909           2018-08-10 00:00:00
99283           2018-10-01 00:00:00
99347           2018-09-27 00:00:00

[160 rows x 8 columns]


Linhas com valores faltantes na coluna 'order_delivered_carrier_date':
                               order_id                       customer_id  \
6      136cce7faa42fdb2cefd53fdc79a6098  ed0271e0b7da060a393796590e7b737a
103    0760a852e4e9d89eb77bf631eaaf1c84  d2a79636084590b7465af8ab374a8cf5
128    15bed8e2fec7fdbadb186b57c46c92f2  f3f0e613e0bdb9c7cee75504f0f90679
266    8e24261a7e58791d10cb1bf9da94df5c  64a254d30eed42cd0e6c36dddb88adf0
324    d3c8851a6651eeff2f73b0e011ac45d0  957f8e082185574de25992dc659ebbc0
...                                 ...                               ...
99283  3a3cddda5a7c27851bd96c3313412840  0b0d6095c5555fe083844281f6b093bb
99313  e9e64a17afa9653aacf2616d94c005b8  b4cd0522e632e481f8eaf766a2646e86
99347  a89abace0dcc01eeb267a9660b5ac126  2f0524a7b1b3845a1a57fcf3910c4333
99348  a69ba794cc7deb415c3e15a0a3877e69  726f0894b5becdf952ea537d5266e543
99415  5fabc81b6322c8443648e1b21a6fef21  32c9df889d41b0ee8309a5efb6855dcb

      order_status order_purchase_timestamp    order_approved_at  \
6         invoiced      2017-04-11 12:22:08  2017-04-13 13:25:17
103       invoiced      2018-08-03 17:44:42  2018-08-07 06:15:14
128     processing      2017-09-03 14:22:03  2017-09-03 14:30:09
266    unavailable      2017-11-16 15:09:28  2017-11-16 15:26:57
324     processing      2016-10-05 22:44:13  2016-10-06 15:51:05
...            ...                      ...                  ...
99283     canceled      2018-08-31 16:13:44                  NaN
99313   processing      2018-01-05 23:07:24  2018-01-09 07:18:05
99347     canceled      2018-09-06 18:45:47                  NaN
99348  unavailable      2017-08-23 16:28:04  2017-08-28 15:44:47
99415  unavailable      2017-10-10 10:50:03  2017-10-14 18:35:57

      order_delivered_carrier_date order_delivered_customer_date  \
6                              NaN                           NaN
103                            NaN                           NaN
128                            NaN                           NaN
266                            NaN                           NaN
324                            NaN                           NaN
...                            ...                           ...
99283                          NaN                           NaN
99313                          NaN                           NaN
99347                          NaN                           NaN
99348                          NaN                           NaN
99415                          NaN                           NaN

      order_estimated_delivery_date
6               2017-05-09 00:00:00
103             2018-08-21 00:00:00
128             2017-10-03 00:00:00
266             2017-12-05 00:00:00
324             2016-12-09 00:00:00
...                             ...
99283           2018-10-01 00:00:00
99313           2018-02-06 00:00:00
99347           2018-09-27 00:00:00
99348           2017-09-15 00:00:00
99415           2017-10-23 00:00:00

[1783 rows x 8 columns]


Linhas com valores faltantes na coluna 'order_delivered_customer_date':
                               order_id                       customer_id  \
6      136cce7faa42fdb2cefd53fdc79a6098  ed0271e0b7da060a393796590e7b737a
44     ee64d42b8cf066f35eac1cf57de1aa85  caded193e8e47b8362864762a83db3c5
103    0760a852e4e9d89eb77bf631eaaf1c84  d2a79636084590b7465af8ab374a8cf5
128    15bed8e2fec7fdbadb186b57c46c92f2  f3f0e613e0bdb9c7cee75504f0f90679
154    6942b8da583c2f9957e990d028607019  52006a9383bf149a4fb24226b173106f
...                                 ...                               ...
99283  3a3cddda5a7c27851bd96c3313412840  0b0d6095c5555fe083844281f6b093bb
99313  e9e64a17afa9653aacf2616d94c005b8  b4cd0522e632e481f8eaf766a2646e86
99347  a89abace0dcc01eeb267a9660b5ac126  2f0524a7b1b3845a1a57fcf3910c4333
99348  a69ba794cc7deb415c3e15a0a3877e69  726f0894b5becdf952ea537d5266e543
99415  5fabc81b6322c8443648e1b21a6fef21  32c9df889d41b0ee8309a5efb6855dcb

      order_status order_purchase_timestamp    order_approved_at  \
6         invoiced      2017-04-11 12:22:08  2017-04-13 13:25:17
44         shipped      2018-06-04 16:44:48  2018-06-05 04:31:18
103       invoiced      2018-08-03 17:44:42  2018-08-07 06:15:14
128     processing      2017-09-03 14:22:03  2017-09-03 14:30:09
154        shipped      2018-01-10 11:33:07  2018-01-11 02:32:30
...            ...                      ...                  ...
99283     canceled      2018-08-31 16:13:44                  NaN
99313   processing      2018-01-05 23:07:24  2018-01-09 07:18:05
99347     canceled      2018-09-06 18:45:47                  NaN
99348  unavailable      2017-08-23 16:28:04  2017-08-28 15:44:47
99415  unavailable      2017-10-10 10:50:03  2017-10-14 18:35:57

      order_delivered_carrier_date order_delivered_customer_date  \
6                              NaN                           NaN
44             2018-06-05 14:32:00                           NaN
103                            NaN                           NaN
128                            NaN                           NaN
154            2018-01-11 19:39:23                           NaN
...                            ...                           ...
99283                          NaN                           NaN
99313                          NaN                           NaN
99347                          NaN                           NaN
99348                          NaN                           NaN
99415                          NaN                           NaN

      order_estimated_delivery_date
6               2017-05-09 00:00:00
44              2018-06-28 00:00:00
103             2018-08-21 00:00:00
128             2017-10-03 00:00:00
154             2018-02-07 00:00:00
...                             ...
99283           2018-10-01 00:00:00
99313           2018-02-06 00:00:00
99347           2018-09-27 00:00:00
99348           2017-09-15 00:00:00
99415           2017-10-23 00:00:00

[2965 rows x 8 columns]

In [85]:
orders_df['order_approved_at'] = orders_df['order_approved_at'].fillna(0)
#Handling missing values in 'orders_df'
missing_values = orders_df.isnull().sum()
missing_values = missing_values[missing_values>0]
mv_cols = missing_values.index
#orders_df[mv_cols].isnull().any()
orders_df[orders_df[mv_cols[0]].isnull()]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
266,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaN,NaN,2017-12-05 00:00:00
324,d3c8851a6651eeff2f73b0e011ac45d0,957f8e082185574de25992dc659ebbc0,processing,2016-10-05 22:44:13,2016-10-06 15:51:05,NaN,NaN,2016-12-09 00:00:00
...,...,...,...,...,...,...,...,...
99283,3a3cddda5a7c27851bd96c3313412840,0b0d6095c5555fe083844281f6b093bb,canceled,2018-08-31 16:13:44,0,NaN,NaN,2018-10-01 00:00:00
99313,e9e64a17afa9653aacf2616d94c005b8,b4cd0522e632e481f8eaf766a2646e86,processing,2018-01-05 23:07:24,2018-01-09 07:18:05,NaN,NaN,2018-02-06 00:00:00
99347,a89abace0dcc01eeb267a9660b5ac126,2f0524a7b1b3845a1a57fcf3910c4333,canceled,2018-09-06 18:45:47,0,NaN,NaN,2018-09-27 00:00:00
99348,a69ba794cc7deb415c3e15a0a3877e69,726f0894b5becdf952ea537d5266e543,unavailable,2017-08-23 16:28:04,2017-08-28 15:44:47,NaN,NaN,2017-09-15 00:00:00
99415,5fabc81b6322c8443648e1b21a6fef21,32c9df889d41b0ee8309a5efb6855dcb,unavailable,2017-10-10 10:50:03,2017-10-14 18:35:57,NaN,NaN,2017-10-23 00:00:00